"""Wavefront OBJ geometry for the demo pack.

Small solids built from boxes, so each version changes the model in a way that
is visible in Chronicle's 3D viewer and in its SVG thumbnail: a taller block, a
new tier, an added plate.

OBJ is plain text with 1-based indices, so the files diff readably and need no
exporter.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Box:
    """An axis-aligned box, by its minimum corner and its size."""

    x: float
    y: float
    z: float
    width: float
    height: float
    depth: float
    group: str = "part"


# The six faces of a box as indices into its eight corners, wound so the
# normals point outward.
_FACES = (
    (0, 1, 2, 3),  # bottom
    (4, 7, 6, 5),  # top
    (0, 4, 5, 1),  # front
    (1, 5, 6, 2),  # right
    (2, 6, 7, 3),  # back
    (3, 7, 4, 0),  # left
)


def _corners(box: Box) -> list[tuple[float, float, float]]:
    x0, y0, z0 = box.x, box.y, box.z
    x1, y1, z1 = x0 + box.width, y0 + box.height, z0 + box.depth
    return [
        (x0, y0, z0), (x1, y0, z0), (x1, y0, z1), (x0, y0, z1),
        (x0, y1, z0), (x1, y1, z0), (x1, y1, z1), (x0, y1, z1),
    ]


def boxes_to_obj(boxes: list[Box], name: str) -> str:
    """Write a set of boxes as one OBJ file, one group per box."""
    lines = [
        f"# {name} — Chronicle demo asset",
        "# Units: millimetres. Generated by scripts/demo_assets.py.",
        f"o {name}",
    ]
    offset = 1  # OBJ vertex indices are 1-based
    for box in boxes:
        corners = _corners(box)
        lines.append(f"g {box.group}")
        for x, y, z in corners:
            lines.append(f"v {x:g} {y:g} {z:g}")
        for face in _FACES:
            indices = " ".join(str(offset + index) for index in face)
            lines.append(f"f {indices}")
        offset += len(corners)
    return "\n".join(lines) + "\n"


# --- The three OBJ assets --------------------------------------------------


def logo_badge(version: int) -> str:
    """A badge blank: plain plate → chamfer rail added → raised emblem boss."""
    boxes = [Box(0, 0, 0, 60, 8, 60, "plate")]
    if version >= 2:
        boxes.append(Box(-2, 8, -2, 64, 3, 64, "rail"))
    if version >= 3:
        boxes.append(Box(18, 11, 18, 24, 10, 24, "emblem-boss"))
    return boxes_to_obj(boxes, "logo-badge")


def display_stand(version: int) -> str:
    """A riser: one tier → two tiers → two tiers on a wide base plate."""
    boxes = [Box(0, 0, 0, 90, 25, 60, "tier-1")]
    if version >= 2:
        boxes.append(Box(10, 25, 10, 70, 25, 40, "tier-2"))
    if version >= 3:
        boxes.insert(0, Box(-12, -8, -12, 114, 8, 84, "base-plate"))
    return boxes_to_obj(boxes, "display-stand")


def packaging_box(version: int) -> str:
    """A carton: cube → taller carton → taller carton with a lid flap."""
    height = 80 if version == 1 else 120
    boxes = [Box(0, 0, 0, 80, height, 80, "carton")]
    if version >= 3:
        boxes.append(Box(0, height, 0, 80, 4, 96, "lid-flap"))
    return boxes_to_obj(boxes, "packaging-box")
