/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report process health without contacting an external provider.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/annotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Annotate */
        post: operations["annotate_annotate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/embed-text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Text Embedding */
        post: operations["create_text_embedding_embed_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/validate-provider-model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Configuration
         * @description Probe a provider/model/key with the real operation used by its task.
         */
        post: operations["validate_configuration_validate_provider_model_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnnotateRequest */
        AnnotateRequest: {
            /** Provider */
            provider?: string | null;
            /** Model */
            model?: string | null;
            /** Apikey */
            apiKey?: string | null;
            /** Filename */
            fileName: string;
            previous?: components["schemas"]["ImageInput"] | null;
            current: components["schemas"]["ImageInput"];
        };
        /**
         * AnnotateResponse
         * @description C3 annotation plus token usage and the estimated cost of the call.
         */
        AnnotateResponse: {
            /** Summary */
            summary: string;
            /** Changes */
            changes: string[];
            /** Tags */
            tags: string[];
            /** Confidence */
            confidence?: number | null;
            usage?: components["schemas"]["TokenUsage"] | null;
            cost?: components["schemas"]["CostEstimate"] | null;
        };
        /**
         * CostEstimate
         * @description Estimated USD cost of one call from token usage × configured prices.
         */
        CostEstimate: {
            /** Input Usd */
            input_usd?: number | null;
            /** Output Usd */
            output_usd?: number | null;
            /** Total Usd */
            total_usd?: number | null;
            /**
             * Currency
             * @default USD
             * @constant
             */
            currency: "USD";
        };
        /** EmbedTextRequest */
        EmbedTextRequest: {
            /** Provider */
            provider?: string | null;
            /** Model */
            model?: string | null;
            /** Apikey */
            apiKey?: string | null;
            /** Text */
            text: string;
        };
        /** EmbedTextResponse */
        EmbedTextResponse: {
            /** Embedding */
            embedding: number[];
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Dimensions */
            dimensions: number;
            usage?: components["schemas"]["TokenUsage"] | null;
            cost?: components["schemas"]["CostEstimate"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Service
             * @default chronicle-ai
             * @constant
             */
            service: "chronicle-ai";
            /**
             * Version
             * @default 0.1.0
             */
            version: string;
        };
        /**
         * ImageInput
         * @description One PNG or JPEG transported across the local HTTP boundary.
         */
        ImageInput: {
            /** Base64 */
            base64: string;
            /**
             * Mediatype
             * @enum {string}
             */
            mediaType: "image/png" | "image/jpeg";
        };
        /** ServiceErrorDetail */
        ServiceErrorDetail: {
            /**
             * Code
             * @enum {string}
             */
            code: "configuration_error" | "invalid_model_output" | "provider_unavailable" | "provider_timeout" | "provider_error";
            /** Message */
            message: string;
        };
        /** ServiceErrorResponse */
        ServiceErrorResponse: {
            detail: components["schemas"]["ServiceErrorDetail"];
        };
        /**
         * TokenUsage
         * @description Token counts reported by the provider for one call (null when absent).
         */
        TokenUsage: {
            /** Input Tokens */
            input_tokens?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Total Tokens */
            total_tokens?: number | null;
        };
        /**
         * ValidateProviderModelRequest
         * @description A fully specified task configuration to probe against its provider.
         */
        ValidateProviderModelRequest: {
            /**
             * Task
             * @enum {string}
             */
            task: "chat" | "embeddings";
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /**
             * Apikey
             * Format: password
             */
            apiKey: string;
        };
        /** ValidateProviderModelResponse */
        ValidateProviderModelResponse: {
            /** Valid */
            valid: boolean;
            /** Reachable */
            reachable: boolean;
            /**
             * Task
             * @enum {string}
             */
            task: "chat" | "embeddings";
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Message */
            message: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    annotate_annotate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnnotateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnotateResponse"];
                };
            };
            /** @description No provider/model/key configured */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Provider or model output error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
            /** @description Provider integration unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
            /** @description Provider timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
        };
    };
    create_text_embedding_embed_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmbedTextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmbedTextResponse"];
                };
            };
            /** @description No provider/model/key configured */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Provider or model output error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
            /** @description Provider integration unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
            /** @description Provider timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
        };
    };
    validate_configuration_validate_provider_model_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateProviderModelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateProviderModelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
