/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report process health without contacting an external provider.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Capabilities
         * @description Report which annotation formats this build implements.
         *
         *     The desktop app captures and displays more creative formats than the AI
         *     service can annotate. It reads this list instead of assuming, and leaves a
         *     version's annotation job queued while its format is missing here.
         */
        get: operations["capabilities_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/annotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Annotate */
        post: operations["annotate_annotate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/embed-text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Text Embedding */
        post: operations["create_text_embedding_embed_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/embed-texts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Text Embeddings */
        post: operations["create_text_embeddings_embed_texts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/validate-provider-model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Configuration
         * @description Probe a provider/model/key with the real operation used by its task.
         */
        post: operations["validate_configuration_validate_provider_model_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnnotateCapability
         * @description Formats this build can annotate.
         */
        AnnotateCapability: {
            /** Formats */
            formats?: string[];
        };
        /** AnnotateRequest */
        AnnotateRequest: {
            /** Provider */
            provider?: string | null;
            /** Model */
            model?: string | null;
            /** Apikey */
            apiKey?: string | null;
            /** Filename */
            fileName: string;
            /**
             * Format
             * @enum {string}
             */
            format: "png" | "jpg" | "jpeg" | "psd";
            previous?: components["schemas"]["ImageInput"] | null;
            current: components["schemas"]["ImageInput"];
        };
        /**
         * AnnotateResponse
         * @description C3 annotation plus token usage and the estimated cost of the call.
         */
        AnnotateResponse: {
            /** Summary */
            summary: string;
            /** Changes */
            changes: string[];
            /** Tags */
            tags: string[];
            /** Confidence */
            confidence?: number | null;
            usage?: components["schemas"]["TokenUsage"] | null;
            cost?: components["schemas"]["CostEstimate"] | null;
        };
        /**
         * CapabilitiesResponse
         * @description What the running service implements, so the app never guesses.
         *
         *     The desktop app captures and displays more formats than the AI service can
         *     annotate. It asks here rather than assuming, and keeps a version's
         *     annotation job queued while its format is absent from this list.
         */
        CapabilitiesResponse: {
            /**
             * Service
             * @default chronicle-ai
             * @constant
             */
            service: "chronicle-ai";
            /** Version */
            version: string;
            annotate?: components["schemas"]["AnnotateCapability"];
        };
        /**
         * CostEstimate
         * @description Estimated USD cost of one call from token usage × configured prices.
         */
        CostEstimate: {
            /** Input Usd */
            input_usd?: number | null;
            /** Output Usd */
            output_usd?: number | null;
            /** Total Usd */
            total_usd?: number | null;
            /**
             * Currency
             * @default USD
             * @constant
             */
            currency: "USD";
        };
        /** EmbedTextRequest */
        EmbedTextRequest: {
            /** Provider */
            provider?: string | null;
            /** Model */
            model?: string | null;
            /** Apikey */
            apiKey?: string | null;
            /** Text */
            text: string;
        };
        /** EmbedTextResponse */
        EmbedTextResponse: {
            /** Embedding */
            embedding: number[];
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Dimensions */
            dimensions: number;
            usage?: components["schemas"]["TokenUsage"] | null;
            cost?: components["schemas"]["CostEstimate"] | null;
        };
        /**
         * EmbedTextsRequest
         * @description A bounded group embedded by one provider batch request.
         */
        EmbedTextsRequest: {
            /** Provider */
            provider?: string | null;
            /** Model */
            model?: string | null;
            /** Apikey */
            apiKey?: string | null;
            /** Texts */
            texts: string[];
        };
        /** EmbedTextsResponse */
        EmbedTextsResponse: {
            /** Embeddings */
            embeddings: number[][];
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Dimensions */
            dimensions: number;
            usage?: components["schemas"]["TokenUsage"] | null;
            cost?: components["schemas"]["CostEstimate"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Service
             * @default chronicle-ai
             * @constant
             */
            service: "chronicle-ai";
            /** Version */
            version: string;
        };
        /**
         * ImageInput
         * @description Original creative-file bytes or a derived image preview.
         */
        ImageInput: {
            /** Base64 */
            base64: string;
            /**
             * Mediatype
             * @enum {string}
             */
            mediaType: "image/png" | "image/jpeg" | "image/vnd.adobe.photoshop";
            /**
             * Format
             * @enum {string}
             */
            format: "png" | "jpg" | "jpeg" | "psd";
        };
        /** ServiceErrorDetail */
        ServiceErrorDetail: {
            /**
             * Code
             * @enum {string}
             */
            code: "configuration_error" | "unsupported_format" | "extraction_error" | "invalid_model_output" | "provider_unavailable" | "provider_timeout" | "provider_error";
            /** Message */
            message: string;
        };
        /** ServiceErrorResponse */
        ServiceErrorResponse: {
            detail: components["schemas"]["ServiceErrorDetail"];
        };
        /**
         * TokenUsage
         * @description Exact provider usage or provider-tokenizer counts (null when absent).
         */
        TokenUsage: {
            /** Input Tokens */
            input_tokens?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Total Tokens */
            total_tokens?: number | null;
        };
        /**
         * ValidateProviderModelRequest
         * @description A fully specified task configuration to probe against its provider.
         */
        ValidateProviderModelRequest: {
            /**
             * Task
             * @enum {string}
             */
            task: "chat" | "embeddings";
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /**
             * Apikey
             * Format: password
             */
            apiKey: string;
        };
        /** ValidateProviderModelResponse */
        ValidateProviderModelResponse: {
            /** Valid */
            valid: boolean;
            /** Reachable */
            reachable: boolean;
            /**
             * Task
             * @enum {string}
             */
            task: "chat" | "embeddings";
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Message */
            message: string;
            usage?: components["schemas"]["TokenUsage"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    capabilities_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    annotate_annotate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnnotateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnotateResponse"];
                };
            };
            /** @description No provider/model/key configured */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
            /** @description Provider rejected the credential */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
            /** @description Provider rejected the request size */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Provider quota or rate limit reached */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
            /** @description Provider or model output error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
            /** @description Provider integration unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
            /** @description Provider timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
        };
    };
    create_text_embedding_embed_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmbedTextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmbedTextResponse"];
                };
            };
            /** @description No provider/model/key configured */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
            /** @description Provider rejected the credential */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
            /** @description Provider rejected the request size */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Provider quota or rate limit reached */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
            /** @description Provider or model output error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
            /** @description Provider integration unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
            /** @description Provider timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
        };
    };
    create_text_embeddings_embed_texts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmbedTextsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmbedTextsResponse"];
                };
            };
            /** @description No provider/model/key configured */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
            /** @description Provider rejected the credential */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
            /** @description Provider rejected the request size */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Provider quota or rate limit reached */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
            /** @description Provider or model output error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
            /** @description Provider integration unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
            /** @description Provider timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceErrorResponse"];
                };
            };
        };
    };
    validate_configuration_validate_provider_model_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateProviderModelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateProviderModelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
